#默认开发环境
server:
  port: 10010
  servlet:
    context-path: /user
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_service_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: mysql123